version: '3'
services:
  live-config:
    image: alaien/mokulive-config
    ports:
      - "8001:8080"

  live-server-callback:
    image: alaien/mokulive-server-callback
    environment:
      - CONFIG_SERVER_URL=http://192.168.199.139:8001
    ports:
      - "8002:8000"
    depends_on:
      - live-config
    links:
      - live-config

  live-server-nginx:
    image: alaien/mokulive-nginxserver
    environment:
      - CALLBACK_URL=http:\/\/192.168.199.139:8002
    ports:
      - "8099:80"
      - "1935:1935"

  live-server-client:
    image: alaien/mokulive-client
    environment:
      - CONFIG_SERVER_URL=http://192.168.199.139:8001
    ports:
      - "80:8000"
    depends_on:
      - live-config
